Check modules added

diff --git a/QPyLOT b/QPyLOT
--- a/QPyLOT
+++ b/QPyLOT
@@ -1,4 +1,13 @@
 #!/bin/bash
 
-cd src
-python main.py &
+# Test if NumPy, Matplotlib and PyQt5 modules are installed
+if ! $(python -c "import numpy" &> /dev/null); then
+    echo "ERROR:" >&2
+elif ! $(python -c "import matplotlib" &> /dev/null); then
+    echo "ERROR: " >&2
+elif ! $(python -c "import PyQt5" &> /dev/null); then
+    echo "ERROR: " >&2
+else
+    cd src
+    python main.py &
+fi
